{"name": "Создание существующего юзера возвращает ошибку", "status": "passed", "start": 1719759313086, "stop": 1719759313256, "uuid": "0747efbf-fe8e-4c14-b0f3-744d785e3492", "historyId": "83dc965176bbe38540530046dc42c6a6", "testCaseId": "83dc965176bbe38540530046dc42c6a6", "fullName": "tests.test_create_user.TestCreateUser#test_create_existent_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "MacBook-Air-Dasima.local"}, {"name": "thread", "value": "10155-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}