{"name": "Создание юзера без имени возвращает ошибку", "status": "passed", "start": 1719759314113, "stop": 1719759314387, "uuid": "17075f50-7ec1-4ec4-a4c2-2cffe67562a6", "historyId": "62e6cf66e635e9334d0efe5bb794b995", "testCaseId": "62e6cf66e635e9334d0efe5bb794b995", "fullName": "tests.test_create_user.TestCreateUser#test_create_user_without_name", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_user"}, {"name": "subSuite", "value": "TestCreateUser"}, {"name": "host", "value": "MacBook-Air-Dasima.local"}, {"name": "thread", "value": "10155-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_user"}]}